# fly.toml app configuration file generated for notstuck-backend on 2025-03-05T21:40:52-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'notstuck-backend'
primary_region = 'dfw'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
