name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push frontend image
        run: |
          docker build \
            -f frontend/Dockerfile \
            --build-arg NEXT_PUBLIC_BACKEND_URL=${{ secrets.NEXT_PUBLIC_BACKEND_URL }} \
            -t ${{ secrets.DOCKER_USERNAME }}/notstuck-frontend:latest \
            ./frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/notstuck-frontend:latest

      - name: Build and push backend image
        run: |
          docker build \
            -f backend/Dockerfile \
            -t ${{ secrets.DOCKER_USERNAME }}/notstuck-backend:latest \
            ./backend
          docker push ${{ secrets.DOCKER_USERNAME }}/notstuck-backend:latest
