name: Deploy to Fly.io

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out your repository.
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up flyctl (Fly.io CLI) so you can run Fly commands.
      - name: Set up flyctl
        uses: superfly/flyctl-actions/setup-flyctl@v1
        with:
          version: "latest"

      # 3. Deploy the backend app.
      - name: Deploy Backend
        run: flyctl deploy -c backend/fly.toml --remote-only --app notstuck-backend
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_BACKEND }}

      # 4. Deploy the frontend app.
      - name: Deploy Frontend
        run: flyctl deploy -c frontend/fly.toml --remote-only --app notstuck-frontend
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_FRONTEND }}
