name: Deploy to Fly.io

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Install flyctl using the official Fly.io GitHub Action
      - name: Install flyctl
        uses: superfly/flyctl-actions/setup-flyctl@v1
        with:
          version: "latest"

      # 3. Deploy the backend
      - name: Deploy Backend to Fly.io
        working-directory: backend
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_BACKEND }}
        run: flyctl deploy --config fly.toml --remote-only

      # 4. Deploy the frontend
      - name: Deploy Frontend to Fly.io
        working-directory: frontend
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_FRONTEND }}
        run: flyctl deploy --config fly.toml --remote-only
